Add Delete Single Timeseries Measurement Button
USACE/instrumentation-ui pull request #128
Opened 2021-12-21 20:17 UTC by lucasb16-exe

- Create delete single timeseries measurement button

- Implement role filter around upload to timeseries button and delete measurement button

- Adjust dropdown component maxHeight attribute to 700% to prevent off screen overflow

2022-01-03 16:14 UTC, brettpalmberg commented
Thanks @lucasb16-exe !  Wanted to send a quick acknowledgement on this, though I can't look at the PR details / code at this time.  Thanks!

2022-03-16 22:03 UTC, lucasb16-exe commented
PR ready for review/merge to develop

2022-04-12 02:22 UTC, willbreitkreutz requested changes
Overall the code looks good.  I do have a couple comments on some added methods for deleting records.  Ultimately not saying to do a redesign if it's working as expected, but I'd like to get a better understanding of the thought process.

2022-04-12 02:22 UTC, willbreitkreutz commented on src/app-pages/instrument/timeseries/timeseries.js
>  import React, { useState, useRef, useEffect } from 'react';
This component is getting a little too complex, probably time to split it up into smaller more specialized components that can be composed here, would make it easier to keep track of all the logic.

2022-04-12 02:22 UTC, willbreitkreutz commented on src/app-bundles/inclinometer-measurements.js
> +    doDeleteInclinometerMeasurement: ({
I'm not sure why we're not using the built-in delete method `do<bundleName>Delete`

2022-04-12 22:07 UTC, lucasb16-exe commented on src/app-pages/instrument/timeseries/timeseries.js
>  import React, { useState, useRef, useEffect } from 'react';
Will take care of this in a follow up commit

2022-04-12 22:27 UTC, lucasb16-exe commented on src/app-bundles/inclinometer-measurements.js
> +          type: 'INCLINOMETER_MEASUREMENT_ITEM_TO_DELETE',
We can discuss the three remaining comments here if that works since a fix for one is practically identical to the other bundle - 

So there's an existing delete method to use instead of the addons I've made? Is that implied for every bundle? 
Still learning redux bundling and appreciate the clarification/feedback. Functionality is as expected but definitely worth refactoring if that's the case.

2022-04-14 15:39 UTC, willbreitkreutz commented on src/app-bundles/inclinometer-measurements.js
> +          type: 'INCLINOMETER_MEASUREMENT_ITEM_TO_DELETE',
Yeah, this is kind of where things get a little meta and could benefit from better documentation.  The rest-bundle includes a `do<bundle_name>Delete` method that expects an item from the bundle as an argument.  See https://github.com/USACE/instrumentation-ui/blob/develop/src/app-bundles/create-rest-bundle.js#L487 for details on the implementation.  It handles removing the item from the store and doing the remote delete, it just needs a `deleteTemplate` populated in the config, that template can include data from the current URL or from the item to be deleted.  Take a look through the method and let me know if any questions come up.  If it's working as expected we could leave what you have here, but a refactor could simplify things.

2022-09-19 18:31 UTC, KevinJJackson commented
Changed base as we are going through a major package/node upgrade and will be easier to merge there before it hits develop.

2022-09-19 22:00 UTC, merged